### ISSUE TITLE
404 on Mapzen level 13

### ISSUE THREAD

**Issue by bertt** [OsmSharp/VectorTileToBitmapRenderer#1]
When zooming in to level 13 there is an 404 error for example https://vector.mapzen.com/osm/all/13/4343/2340.mvt
response: "Mapzen has released Vector Tiles 1.0. For more information visit: https://mapzen.com/blog/v1-vector-tile-service/"

**Comment by pauldendulk** [comment]
uh, so what should I do? Use a different tile source? Update the protocol? I am sure you can tell me exactly.

**Comment by xivk** [comment]
I think updating to this url scheme should be fine, but there is the need to insert an API key:    

http://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt?api_key=mapzen-xxxxxxx

**Comment by pauldendulk** [comment]
Thanks, Changed the url. Added new mapzen key. Added gzip.
